SP=rule75.cocci

# ice1724.c, just remove pci_set_consistent_dma_mask

SOURCES = ali5451.c \
          als4000.c \
          azt3328.c \
          emu10k1_main.c \
          es1938.c \
          es1968.c \
          ice1712.c \
          ice1724.c \
          maestro3.c \
          memalloc.c \
          sonicvibes.c \
          trident_main.c



include ../generic_makefile
