SP=rule19.cocci

SOURCES = asuscom.c \
avm_a1.c \
avm_a1p.c \
bkm_a4t.c \
bkm_a8.c \
diva.c \
elsa.c \
gazel.c \
hfc_2bds0.c \
hfc_pci.c \
hfc_sx.c \
icc.c \
ipacx.c \
isac.c \
isar.c \
isurf.c \
ix1_micro.c \
jade_irq.c \
mic.c \
niccy.c \
s0box.c \
saphir.c \
sedlbauer.c \
sportster.c \
teleint.c \
teles0.c \
teles3.c \
telespci.c \
w6692.c


include ../generic_makefile
