SP=rule19.cocci

SOURCES = rule19_ver10_gazel.c \
          rule19_ver11_hfc_pci.c \
          rule19_ver12_hfc_sx.c \
          rule19_ver13_hfcscard.c \
          rule19_ver14_isurf.c \
          rule19_ver15_ix1_micro.c \
          rule19_ver16_mic.c \
          rule19_ver17_niccy.c \
          rule19_ver18_nj_s.c \
          rule19_ver19_nj_u.c \
          rule19_ver1_asuscom.c \
          rule19_ver20_s0box.c \
          rule19_ver21_saphir.c \
          rule19_ver22_sedlbauer.c \
          rule19_ver23_sportster.c \
          rule19_ver24_teleint.c \
          rule19_ver25_teles0.c \
          rule19_ver26_teles3.c \
          rule19_ver27_telespci.c \
          rule19_ver28_w6692.c \
          rule19_ver2_avm_a1.c \
          rule19_ver3_avm_a1p.c \
          rule19_ver4_avm_pci.c \
          rule19_ver5_bkm_a4t.c \
          rule19_ver6_bkm_a8.c \
          rule19_ver7_diva.c \
          rule19_ver8_elsa.c \
          rule19_ver9_enternow_pci.c


include ../../generic_makefile
