SP=mini.cocci

SOURCES=3c574_cs.c \
3c589_cs.c \
aha152x_stub.c \
airo_cs.c \
atmel_cs.c \
avma1_cs.c \
avm_cs.c \
axnet_cs.c \
bluecard_cs.c \
bt3c_cs.c \
btuart_cs.c \
cm4000_cs.c \
cm4040_cs.c \
com20020_cs.c \
dtl1_cs.c \
elsa_cs.c \
fdomain_stub.c \
fmvj18x_cs.c \
hostap_cs.c \
ibmtr_cs.c \
ide-cs.c \
ixj_pcmcia.c \
netwave_cs.c \
nmclan_cs.c \
orinoco_cs.c \
parport_cs.c \
pcmciamtd.c \
pcnet_cs.c \
pdaudiocf.c \
qlogic_stub.c \
ray_cs.c \
sedlbauer_cs.c \
serial_cs.c \
sl811_cs.c \
smc91c92_cs.c \
spectrum_cs.c \
sym53c500_cs.c \
synclink_cs.c \
teles_cs.c \
vxpocket.c \
wavelan_cs.c \
wl3501_cs.c \
xirc2ps_cs.c \
nsp_cs.c

include ../generic_makefile
