CEDESCRIPTION="add argument to scsi_cmd_ioctl"
SP=rule84.cocci

SOURCES = cdu31a.c \
cm206.c \
ide-cd.c \
ide-disk.c \
ide-floppy.c \
ide-scsi.c \
ide-tape.c \
mcd.c \
mcdx.c \
pcd.c \
sbpcd.c \
sd.c \
sr.c \
st.c \
viocd.c

include ../generic_makefile
