#
# Make file for rule 10
#

# Semantic Patch file
SP=rule10.cocci

# The C files
SOURCES = ec.c       \
	  evgpeblk.c \
	  evgpe.c    \
	  hwgpe.c    \
	  hwregs.c   \
	  hwtimer.c

# NOT in SOURCES according to Yoann:
#
#   rsxface.c
#   tbconvrt.c


#
include ../generic_makefile
