CEDESCRIPTION="factorize code via sg_address"
SP=rule71.cocci

SOURCES = debug.c \
freecom.c \
isd200.c \
protocol.c \
raw_bulk.c \
scsiglue.c \
sddr09.c \
transport.c \
usb.c

include ../generic_makefile
