#!/bin/sh
if [ "$1" = "--ignore_localversion" ]; then
	export MAKE_COCCI_RELEASE="y"
else
	unset MAKE_COCCI_RELEASE
fi
aclocal -I setup
autoconf -Wall
( cd bundles/stdcompat/stdcompat-current && \
  autoheader && aclocal && automake && autoconf -Wall )
