echo setting COCCINELLE_HOME
setenv COCCINELLE_HOME `pwd`

echo setting LD_LIBRARY_PATH
setenv LD_LIBRARY_PATH $COCCINELLE_HOME:$LD_LIBRARY_PATH

echo setting PYTHONPATH
setenv PYTHONPATH $COCCINELLE_HOME/python:$PYTHONPATH

setenv PATH $COCCINELLE_HOME:$PATH
