
##############################################################################
# Website targets
##############################################################################

WEBBASE=~/website
WEBSITE=$(WEBBASE)/distrib

website:
	cp $(TMP)/$(PACKAGE).tgz                $(WEBSITE)
	cp $(TMP)/$(PACKAGE)-bin-x86.tgz        $(WEBSITE)
#	cp $(TMP)/$(PACKAGE)-bin-x86-static.tgz $(WEBSITE)
	cp $(TMP)/$(PACKAGE)-bin-x86-python.tgz $(WEBSITE)
	cp $(TMP)/$(PACKAGE)-bin-bytecode-$(OCAMLVERSION).tgz          $(WEBSITE)
	cp $(TMP)/$(PACKAGE)-bin-bytecode-$(OCAMLVERSION)-python.tgz   $(WEBSITE)
	cd $(WEBSITE); svn add $(PACKAGE).tgz               \
		$(PACKAGE)-bin-x86.tgz                      \
		$(PACKAGE)-bin-x86-python.tgz               \
		$(PACKAGE)-bin-bytecode-$(OCAMLVERSION).tgz \
		$(PACKAGE)-bin-bytecode-$(OCAMLVERSION)-python.tgz
#		$(PACKAGE)-bin-x86-static.tgz
	$(MAKE) -C docs/manual WEBBASE=$(WEBBASE) install
	@echo "\nYou need to manually update those files:\n"
	@echo "\t$(WEBBASE)/download.php"
	@echo "\t$(WEBSITE)/change.html\n"
	@echo "Then commit the changes.\n"
#	rm -f $(WEBSITE)/LATEST* $(WEBSITE)/coccinelle-latest.tgz
#	cp changes.txt $(WEBSITE)/changes-$(VERSION).txt
#	cd $(WEBSITE); touch LATEST_IS_$(VERSION); ln -s $(PACKAGE).tgz coccinelle-latest.tgz
#	cp readme.txt $(WEBSITE)

##############################################################################
# Targets to update PPA
##############################################################################

UBUNTU=precise
UBUNTURELEASE=$(UBUNTU:%=ubuntu-%)

.PHONY:: ubuntu $(UBUNTURELEASE)

ubuntu:
	for r in $(UBUNTURELEASE); do $(MAKE) $$r ; done
	@echo "\nYou can now build the Ubuntu source package with\n"
	@echo "\tmake packsrc\n"

#$(UBUNTURELEASE):
#	debchange -c debian/changelog.karmic -D karmic -v $(VERSION)~$(@:ubuntu-%=%)~npalix1 "New release $(VERSION)"
IDX?=1

ubuntu-precise:
	debchange -c debian/changelog -D precise -v $(VERSION)~1204npalix$(IDX) "New release $(VERSION)"

ubuntu-new:
	if [ ! -f debian/changelog ] ; then \
		debchange --create -c debian/changelog \
			-v $(VERSION)~npalix$(IDX) "New release $(VERSION)" \
			--package $(PRJNAME) --distribution $(DISTRIB_CODENAME); \
	else \
		debchange -c debian/changelog -D $(DISTRIB_CODENAME) -v $(VERSION)~npalix$(IDX) "New release $(VERSION)" ; \
	fi

