SP=rule17.cocci

SOURCES = amd7930.c \
          amd7930_fn.c \
	  avm_pci.c \
	  config.c \
	  elsa_ser.c \
	  hfc_2bds0.c \
	  hfc_2bs0.c \
	  hfc_pci.c \
	  hfc_sx.c \
	  hscx.c \
	  icc.c \
	  ipacx.c \
	  isac.c \
	  isar.c \
	  isdnl1.c \
	  jade.c \
	  netjet.c \
	  w6692.c


include ../../generic_makefile
