#!/bin/tcsh

setenv PYTHONPATH ${HOME}/coccinelle
setenv LD_LIBRARY_PATH ${HOME}/coccinelle

(~/coccinelle/spatch.opt -allow_inconsistent_paths -quiet -timeout 120 \
-dir /code/linux-2.6 -use_glimpse -cocci_file $* > ${1:r}.${3}.out) \
>& tmp.${1:r}.${3}.out
