SP=rule50.cocci

SOURCES = dbcmds.c \
dbdisply.c \
dbstats.c \
dsmthdat.c \
dsobject.c \
dsopcode.c \
dsutils.c \
dswexec.c \
dswstate.c \
evregion.c \
evrgnini.c \
evxface.c \
exconfig.c \
exconvrt.c \
excreate.c \
exdump.c \
exfield.c \
exfldio.c \
exmisc.c \
exoparg1.c \
exoparg2.c \
exoparg3.c \
exoparg6.c \
exprep.c \
exresnte.c \
exresolv.c \
exresop.c \
exstore.c \
exstoren.c \
exutils.c \
hwregs.c \
nsaccess.c \
nsdump.c \
nseval.c \
nsobject.c \
nssearch.c \
nsutils.c \
psopcode.c \
rscalc.c \
rscreate.c \
rsutils.c \
tbutils.c \
utcopy.c \
utdelete.c \
uteval.c \
utglobal.c \
utils.c \
utmisc.c \
utobject.c

include ../generic_makefile
