CEDESCRIPTION="reorganize fields of input_dev/gameport structures"
SP=rule52.cocci

SOURCES = a3d.c \
adbhid.c \
adi.c \
aiptek.c \
amijoy.c \
amikbd.c \
amimouse.c \
analog.c \
atkbd.c \
cobra.c \
cs461x.c \
db9.c \
emu10k1-gp.c \
evdev.c \
fm801-gp.c \
gamecon.c \
gf2k.c \
grip.c \
guillemot.c \
gunze.c \
h3600_ts_input.c \
hid-input.c \
iforce-main.c \
inport.c \
input.c \
interact.c \
lightning.c \
logibm.c \
mac_hid.c \
magellan.c \
maple_keyb.c \
newtonkbd.c \
ns558.c \
pc110pad.c \
powermate.c \
ps2serkbd.c \
psmouse.c \
rpcmouse.c \
sermouse.c \
sidewinder.c \
spaceball.c \
spaceorb.c \
stinger.c \
sunkbd.c \
tmdc.c \
turbografx.c \
twidjoy.c \
uinput.c \
usbkbd.c \
usbmouse.c \
vortex.c \
wacom.c \
warrior.c \
xpad.c \
xtkbd.c

include ../generic_makefile
