CEDESCRIPTION="replace remap_page_range"
SP=rule81.cocci

SOURCES = ali5455.c \
atyfb_base.c \
au1000.c \
audio.c \
cmpci.c \
cpia.c \
cs4281m.c \
cs46xx.c \
es1370.c \
es1371.c \
esssolo1.c \
flash.c \
forte.c \
frontend.c \
ftape-ctl.c \
gbefb.c \
hpet.c \
i810_audio.c \
i810_dma.c \
i830_dma.c \
igafb.c \
ite8172.c \
jsflash.c \
maestro3.c \
maestro.c \
mem.c \
meye.c \
mmtimer.c \
ov511.c \
planb.c \
rme96xx.c \
se401.c \
sgivwfb.c \
sn9c102_core.c \
sonicvibes.c \
soundcard.c \
stv680.c \
trident.c \
usbvideo.c \
vicam.c \
video1394.c \
w9968cf.c \
ymfpci.c \
zoran_driver.c \
zr36120.c

include ../generic_makefile
