SP=rule9.cocci

SOURCES = cciss_scsi.c \
          sbpc2.c \
          53c700.c \
          acornscsi.c \
          arxescsi.c \
          cumana_2.c \
          eesox.c \
          powertec.c \
          cpqfcTSinit.c \
          eata_pio.c \
          fcal.c \
          g_NCR5380.c \
          in2000.c \
          ncr53c8xx.c \
          nsp32.c \
          nsp_cs.c \
          sym53c8xx.c \
          sym_glue.c \
          scsiglue.c 

SOURCES = scsiglue.c 53c700.c

include ../../generic_makefile
