CEDESCRIPTION="change in arguments of usb_(de)register_dev"
SP=rule41.cocci

SOURCES = auerswald.c \
brlvger.c \
dabusb.c \
hiddev.c \
mdc800.c \
printer.c \
rio500.c \
scanner.c \
usb-skeleton.c

include ../generic_makefile
