CEDESCRIPTION="drop argument pnp_activate_dev"
#
# Make file for rule38
#

# Semantic Patch file
SP=rule38.cocci

# The C files

SOURCES = 3c509.c          \
	  3c515.c	   \
	  ad1848.c	   \
	  aha152x.c	   \
	  aha1542.c	   \
	  asuscom.c	   \
	  avm_pci.c	   \
	  diva.c	   \
	  elsa.c	   \
	  g_NCR5380.c	   \
	  hfcscard.c	   \
	  hfc_sx.c	   \
	  i82365.c	   \
	  isurf.c	   \
	  ix1_micro.c	   \
	  ixj.c		   \
	  ne.c		   \
	  niccy.c	   \
	  radio-sf16fmi.c  \
	  sb1000.c	   \
	  sedlbauer.c	   \
	  smc-ultra.c	   \
	  sym53c416.c      \
	  teles3.c


# 
include ../generic_makefile
