CEDESCRIPTION="usb_submit_urb"
SP=usu.cocci

SOURCES = CDCEther.c \
          acm.c \
          audio.c \
          auerswald.c \
          belkin_sa.c \
          bluetooth.c \
          catc.c \
          cpia_usb.c \
          cyberjack.c \
          dabusb.c \
          devio.c \
          digi_acceleport.c \
          empeg.c \
          ftdi_sio.c \
          hcd.c \
          hci_usb.c \
          hid-core.c \
          hpusbscsi.c \
          hub.c \
          iforce.c \
          io_edgeport.c \
          ipaq.c \
          ir-usb.c \
          irda-usb.c \
          kaweth.c \
          keyspan.c \
          keyspan_pda.c \
          kl5kusb105.c \
          mct_u232.c \
          mdc800.c \
          microtek.c \
          omninet.c \
          ov511.c \
          pegasus.c \
          pl2303.c \
          printer.c \
          pwc-if.c \
          scanner.c \
          scsiglue.c \
          se401.c \
          st5481_b.c \
          st5481_d.c \
          st5481_usb.c \
          stv680.c \
          transport.c \
          uhci.c \
          usb-ohci.c \
          usb-skeleton.c \
          usb-uhci.c \
          usb.c \
          usbkbd.c \
          usbmouse.c \
          usbnet.c \
          usbserial.c \
          usbvideo.c \
          vicam.c \
          visor.c \
          wacom.c \
          whiteheat.c

include ../generic_makefile
