CEDESCRIPTION="replace kmalloc/memset by kzalloc"
SP=rule94.cocci

SOURCES = auerswald.c \
cp2101.c \
cypress_m8.c \
ehci-mem.c \
ehci-sched.c \
ftdi_sio.c \
garmin_gps.c \
hc_crisv10.c \
io_edgeport.c \
io_ti.c \
ir-usb.c \
keyspan.c \
kobil_sct.c \
mct_u232.c \
mon_main.c \
mon_text.c \
option.c \
ov511.c \
pl2303.c \
pwc-if.c \
se401.c \
stv680.c \
ti_usb_3410_5052.c \
usblcd.c \
usb-serial.c \
usbtest.c \
visor.c \
zd1201.c \
 \
bcm203x.c \
bfusb.c \
bluecard_cs.c \
bpa10x.c \
bt3c_cs.c \
btuart_cs.c \
dtl1_cs.c \
hci_bcsp.c \
hci_h4.c \
hci_ldisc.c \
hci_usb.c \
hci_vhci.c

include ../generic_makefile
