CEDESCRIPTION="rename (Un)LockPage and related functions"
#
# Make file for rule 42
#

# Semantic Patch file
SP=rule42.cocci

# The C files
SOURCES = 10_symlink.c  \
	  11_compress.c	\
	  12_inode.c	\
	  13_inode.c	\
	  14_inode.c	\
	  15_dir.c	\
	  16_file.c	\
	  17_dir.c	\
	  18_file.c	\
	  19_inode.c	\
	  1_symlink.c	\
	  20_symlink.c	\
	  21_dir.c	\
	  22_inode.c	\
	  2_symlink.c	\
	  3_inode.c	\
	  4_file.c	\
	  5_dir.c	\
	  6_namei.c	\
	  7_dir.c	\
	  8_symlink.c	\
	  9_dir.c	\
	  agpgart_be.c	\
	  aops.c	\
	  blkmtd.c	\
	  buffer.c	\
	  cache.c	\
	  check.c	\
	  compress.c	\
	  dir.c		\
	  emd.c		\
	  file.c	\
	  filemap.c	\
	  i810_dma.c	\
	  inode.c	\
	  inode-v23.c	\
	  ioctl.c	\
	  jfs_metapage.c\
	  loop.c	\
	  lvm-snap.c	\
	  md.c		\
	  memory.c	\
	  mincore.c	\
	  namei.c	\
	  page_alloc.c	\
	  page_io.c	\
	  page-writeback.c \
	  rd.c		\
	  read.c	\
	  rock.c	\
	  shmem.c	\
	  slab.c	\
	  super.c	\
	  swapfile.c	\
	  swap_state.c	\
	  symlink.c	\
	  tail_conversion.c \
	  vmscan.c	\
	  vxfs_immed.c	\
	  vxfs_subr.c   \
	  write.c


#
include ../generic_makefile
