#
# Make file for rule30
#

# Semantic Patch file
SP=rule30.cocci

# Alternative (does additional clean-up)
#SP=rule17full.cocci

# The C files
SOURCES = acsi.c \
          amiflop.c \
	  ataflop.c \
	  aztcd.c \
	  cdu31a.c \
	  cm206.c \
	  fd1772.c \
	  ftl.c \
	  gscd.c \
	  hd.c \
	  jsflash.c \
	  mcd.c \
	  mcdx.c \
	  mfmhd.c \
	  nftlcore.c \
	  optcd.c \
	  pcd.c \
	  pd.c \
	  pf.c \
	  ps2esdi.c \
	  sbpcd.c \
	  sjcd.c \
	  sonycd535.c \
	  swim3.c \
	  swim_iop.c \
	  xd.c \
	  xpram.c \
	  z2ram.c


# 
include ../generic_makefile

