CEDESCRIPTION="replace deg_get/set_drvdata"
SP=rule8.cocci

SOURCES = aiptek.c \
audio.c \
auerswald.c \
bluetty.c \
brlvger.c \
catc.c \
cdc-acm.c \
cdc-ether.c \
cpia_usb.c \
dabusb.c \
devio.c \
dsbr100.c \
hci_usb.c \
hid-core.c \
hpusbscsi.c \
hub.c \
ibmcam.c \
iforce-usb.c \
irda-usb.c \
kaweth.c \
konicawc.c \
mdc800.c \
microtek.c \
ov511.c \
pegasus.c \
powermate.c \
pwc-if.c \
rio500.c \
rtl8150.c \
scanner.c \
se401.c \
speedtouch.c \
st5481_init.c \
stv680.c \
tiglusb.c \
ultracam.c \
usbaudio.c \
usb.c \
usbkbd.c \
usblcd.c \
usblp.c \
usb-midi.c \
usbmouse.c \
usbnet.c \
usb-serial.c \
usb-skeleton.c \
usbtest.c \
usbvideo.c \
uss720.c \
vicam.c \
wacom.c \
xpad.c

include ../generic_makefile
