SP=schedev.cocci

SOURCES = avm_pci.c \
          config.c \
          diva.c \
          elsa_ser.c \
          hfc_2bds0.c \
          hfc_2bs0.c \
          hfc_pci.c \
          hfc_sx.c \
          hscx.c \
          hscx_irq.c \
          ipacx.c \
          isar.c \
          jade_irq.c \
          netjet.c \
          w6692.c

include ../../generic_makefile
