CEDESCRIPTION="eliminating refrigerator calls"
SP=rule93.cocci

SOURCES = 8139too.c \
airo.c \
core.c \
cs.c \
dvb_frontend.c \
file_storage.c \
gameport.c \
hub.c \
ieee1394_core.c \
md.c \
msp3400.c \
nodemgr.c \
pktcdvd.c \
serio.c \
sir_kthread.c \
stir4200.c \
therm_adt746x.c \
usb.c \
video-buf-dvb.c \
w1.c

include ../generic_makefile
