SP=schedev.cocci

SOURCES = amd7930_fn.c \
          config.c \
          hfc_2bds0.c \
          hfc_pci.c \
          hfc_sx.c \
          icc.c \
          ipacx.c \
          isac.c \
          jade.c \
          w6692.c

include ../../generic_makefile
