CEDESCRIPTION="rename and reorganize calls to scsi_set_pci_device"
SP=rule57.cocci

SOURCES = 3w-xxxx.c \
advansys.c \
aic79xx_osm.c \
aic7xxx_old.c \
aic7xxx_osm.c \
AM53C974.c \
cciss_scsi.c \
cpqfcTSinit.c \
dmx3191d.c \
fdomain.c \
ips.c \
linit.c \
megaraid.c \
mptscsih.c \
nsp32.c \
pci2000.c \
pci2220i.c \
qla1280.c \
qlogicfc.c \
qlogicisp.c \
sym53c8xx.c \
sym_glue.c \
tmscsim.c

include ../generic_makefile
