CEDESCRIPTION="remove blk_clear() calls"
SP=rule62.cocci


# ll_rw_blk.c: related to the E (remove of blk_size global variable).

# thought mentions in addition this:
#  "drivers/md/lvm.c: as usual, not updated"

SOURCES = DAC960.c \
          amiflop.c \
          dasd_genhd.c \
          ftl.c \
          ide.c \
          md.c \
          ps2esdi.c \
          rd.c \
          sd.c \
          sr.c \
          xd.c \
          xpram.c


include ../generic_makefile
