SP=rule7.cocci

SOURCES = adm1021.c \
adv7175.c \
bt819.c \
bt856.c \
bttv-if.c \
lm75.c \
msp3400.c \
saa5249.c \
saa7110.c \
saa7111.c \
saa7134-i2c.c \
saa7185.c \
tda7432.c \
tda9875.c \
tda9887.c \
tuner-3036.c \
tuner.c \
tvaudio.c

include ../generic_makefile
