CEDESCRIPTION="add bt_cb around pkt_type field access"
SP=rule101.cocci

SOURCES=bfusb.c \
bluecard_cs.c \
bpa10x.c \
bt3c_cs.c \
btuart_cs.c \
dtl1_cs.c \
hci_bcsp.c \
hci_h4.c \
hci_ldisc.c \
hci_usb.c \
hci_vhci.c

include ../generic_makefile
