CEDESCRIPTION="drop major() test in current_valid functions"
#
# Make file for rule33
#

# Semantic Patch file
SP=rule33.cocci

# The C files

SOURCES = aztcd.c \
	  mcd.c	  \
	  optcd.c \
          sjcd.c


# 
include ../generic_makefile
