SP=check_region.cocci

SOURCES = aztcd.c \
          cdrom.c \
          cdu31a.c \
          cm206.c \
          gscd.c \
          isp16.c \
          mcd.c \
          mcdx.c \
          optcd.c \
          sbpcd2.c \
          sbpcd3.c \
          sbpcd4.c \
          sbpcd.c \
          sjcd.c \
          sonycd535.c


include ../../generic_makefile
