#
# Make file for rule31
#

# Semantic Patch file
SP=rule31.cocci

# The C files
SOURCES = acsi.c        \
	  amiflop.c	\
	  ataflop.c	\
	  cdu31a.c	\
	  cm206.c	\
	  fd1772.c	\
	  ftl.c		\
	  gscd.c	\
	  hd.c		\
	  jsflash.c	\
	  mcdx.c	\
	  mfmhd.c	\
	  mtdblock.c	\
	  mtdblock_ro.c \
	  nftlcore.c	\
	  pcd.c		\
	  pd.c		\
	  pf.c		\
	  ps2esdi.c	\
	  sbpcd.c	\
	  sonycd535.c	\
	  swim3.c	\
	  swim_iop.c	\
	  xd.c		\
	  xpram.c	\
	  z2ram.c


# 
include ../../generic_makefile
