CEDESCRIPTION="reorganize register_pccard_driver protocol"
SP=rule20.cocci

SOURCES = 3c574_cs.c \
3c589_cs.c \
8250_cs.c \
avma1_cs.c \
avm_cs.c \
axnet_cs.c \
bluecard_cs.c \
bt3c_cs.c \
btuart_cs.c \
com20020_cs.c \
dtl1_cs.c \
elsa_cs.c \
fdomain_stub.c \
fmvj18x_cs.c \
ibmtr_cs.c \
ide-cs.c \
netwave_cs.c \
nmclan_cs.c \
orinoco_cs.c \
parport_cs.c \
pcmciamtd.c \
pcnet_cs.c \
qlogic_stub.c \
sedlbauer_cs.c \
smc91c92_cs.c \
synclink_cs.c \
wavelan_cs.c \
xirc2ps_cs.c

include ../generic_makefile
