SP=rule92.cocci

SOURCES=airprime.c \
belkin_sa.c \
bus.c \
cp2101.c \
cyberjack.c \
cypress_m8.c \
digi_acceleport.c \
empeg.c \
ftdi_sio.c \
garmin_gps.c \
generic.c \
hp4x.c \
io_ti.c \
ipaq.c \
ipw.c \
ir-usb.c \
keyspan_pda.c \
kl5kusb105.c \
kobil_sct.c \
mct_u232.c \
omninet.c \
option.c \
pl2303.c \
safe_serial.c \
ti_usb_3410_5052.c \
usb-serial.c \
visor.c \
whiteheat.c

include ../generic_makefile
