CEDESCRIPTION="rename fields in PStack structure and getters introduction"
SP=rule35.cocci

# 2 new files:
#  hisax_fcclassic.c
#  hisax_hscx.c

SOURCES = avm_pci.c \
	  callc.c \
          config.c \
          elsa_ser.c \
          hfc_2bds0.c \
          hfc_2bs0.c \
          hfc_pci.c \
          hfc_sx.c \
          hscx.c \
          icc.c \
          isac.c \
          isar.c \
          isdnl1.c \
          isdnl2.c \
          isdnl3.c \
          jade.c \
          l3_1tr6.c \
          l3dss1.c \
          l3ni1.c \
          netjet.c \
          st5481_d.c \
          st5481_usb.c \
          tei.c \
          w6692.c

include ../generic_makefile
