SP=rule27.cocci

SOURCES = avm_pci.c \
callc.c \
config.c \
elsa_ser.c \
hfc_2bds0.c \
hfc_2bs0.c \
hfc_pci.c \
hfc_sx.c \
hscx.c \
ipacx.c \
isar.c \
isdnl1.c \
jade.c \
netjet.c \
w6692.c

include ../generic_makefile
