SP=atomic_dec.cocci

# fixed versions have the overlooked calls to atomic_dec fixed as they are
# done in Linux 2.6.10

SOURCES = multipath.c \
          raid1.c \
          raid5.c \
          raid6main.c \
	  multipath_fixed.c \
          raid1_fixed.c \
          raid5_fixed.c \
          raid6main_fixed.c

include ../generic_makefile
