CEDESCRIPTION="rename and reorganize calls to atomic_dec"
SP=atomic_dec.cocci

# fixed versions have the overlooked calls to atomic_dec fixed as they are
# done in Linux 2.6.10

SOURCES = multipath.c \
          raid1.c \
          raid5.c \
          raid6main.c

include ../generic_makefile
