#
# Make file for rule36
#

# Semantic Patch file
SP=rule36.cocci

# The C files

SOURCES = 1_usb.c     \
	  cdc-ether.c \
	  hcd.c	      \
	  pegasus.c   \
	  uhci.c      \
	  usb.c	      \
	  usbnet.c    \
	  usb-ohci.c  \
	  usb-uhci.c  \
	  usbvideo.c

# 
include ../../generic_makefile
